services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'spm_pi_db'
    volumes:
      - ./database_usuarios.sql:/docker-entrypoint-initdb.d/database_usuarios.sql
    ports:
      - "3307:3306"

  pythonapp:
    build: .
    depends_on:
      - mysql
    ports:
      - "4000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
